version: 2

defaults: &defaults
  machine: true
  working_directory: ~/app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: ./scripts/build.sh
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: ./scripts/build.sh
      - run: DEPLOY_ENV=prd ./scripts/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  prd:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\bv(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:-[\da-z-]+(?:\.[\da-z-]+)*)?(?:\+[\da-z-]+(?:\.[\da-z-]+)*)?\b/
